version: '2'
services:
  dns:
    image: lancachenet/lancache-dns:latest
    env_file: .env
#    restart: unless-stopped
    ports:
      - ${DNS_BIND_IP}:53:53/udp
    environment:
      - TZ=${TZ}
  sniproxy:
    image: lancachenet/sniproxy:latest
    env_file: .env
#    restart: unless-stopped
    ports:
      - 443:443/tcp
    environment:
      - TZ=${TZ}
  monolithic:
    image: lancachenet/monolithic:latest
    env_file: .env
#    restart: unless-stopped
    ports:
      - 80:80/tcp
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
    environment:
      - TZ=${TZ}
